name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Setup Expo CLI
        run: npm install -g @expo/cli
        
      - name: Setup EAS CLI
        run: npm install -g eas-cli
        
      - name: Extract version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
        
      - name: Update app version
        run: |
          npm version ${{ steps.version.outputs.VERSION }} --no-git-tag-version
          
      - name: Build production
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas build --platform all --profile production --non-interactive
        
      - name: Submit to app stores
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        run: eas submit --platform all --profile production --non-interactive
        
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ steps.version.outputs.VERSION }}
          body: |
            ## Cambios en esta versión
            
            ### Nuevas características
            - Lista de nuevas características
            
            ### Correcciones
            - Lista de correcciones de bugs
            
            ### Mejoras
            - Lista de mejoras
            
            ## Instalación
            
            ### Android
            Descarga el APK desde los assets de esta release.
            
            ### iOS
            Disponible en el App Store.
          draft: false
          prerelease: false
